import { browser, $, expect } from '@wdio/globals'
import login from '../page-objects/login.page.js'
import workItems from '../page-objects/work-items.page.js'

/**
 * Create work item page — field-level behaviour.
 *
 * RA-219 moved application-reference generation out of the client: the
 * reference is no longer rendered on the create form and is generated by
 * the case management backend on submission. This spec therefore checks:
 *   • The create form does NOT expose an application reference input
 *     (the user neither sees nor supplies it).
 *   • Email field exists and is pre-filled with `test@defra.gov.uk`.
 *   • Email field validates format on submit and shows an inline error
 *     for an invalid address (negative path, no redirect).
 *
 * The happy-path submission and the server-generated reference shown on
 * the success banner are covered by `ra-219-server-side-application-reference`
 * and the `management.e2e.js` journey.
 */
describe('create work item: application reference + email fields', () => {
  before(async () => {
    await login.loginAs('assign')
  })

  after(async () => {
    await login.logout()
  })

  it('does not render an application reference field and seeds the default operatorEmail', async () => {
    await workItems.goto()
    await workItems.clickCreateWorkItem()

    // RA-219: the reference is generated server-side; there must be no
    // applicationReference input on the form for the user to see or edit.
    const refInput = await $('#field-applicationReference')
    expect(await refInput.isExisting()).toBe(false)

    const operatorEmailInput = await $('#field-operatorEmail')
    expect(await operatorEmailInput.getValue()).toBe('test@defra.gov.uk')
  })

  it('rejects an invalid operatorEmail address with an inline error', async () => {
    await workItems.goto()
    await workItems.clickCreateWorkItem()

    // Replace the seeded default with something obviously bad.
    const operatorEmailInput = await $('#field-operatorEmail')
    await operatorEmailInput.setValue('not-an-email')

    await $('#field-organisationName').setValue('RA-172 Test Co')
    await $('#field-siteAddress-line1').setValue('1 Validation Way')
    await $('#field-siteAddress-town').setValue('Testville')
    await $('#field-siteAddress-postcode').setValue('TS1 1AA')
    await $('#field-material').selectByAttribute('value', 'plastic')
    await $('#field-tonnageBand').selectByAttribute('value', '0-500')
    await $('[data-testid="create-work-item-submit"]').click()

    // The page should re-render with the error summary still mounted
    // and the email-specific message visible somewhere on the page.
    const summary = await $('[data-testid="create-work-item-error-summary"]')
    await expect(summary).toBeDisplayed()
    await expect(summary).toHaveText(
      expect.stringContaining(
        'Enter an email address in the correct format, like name@example.com'
      )
    )

    // We must still be on the create page (no redirect on validation
    // failure).
    expect(await browser.getUrl()).toEqual(
      expect.stringContaining('/work-items/re-accreditation/new')
    )
  })
})
