import { expect } from '@wdio/globals'
import login from '../page-objects/login.page.js'
import workItems from '../page-objects/work-items.page.js'
import detail from '../page-objects/work-item-detail.page.js'

/**
 * RA-219 — Application reference generated by the case management system.
 *
 * The client (BFF) no longer generates or submits an application
 * reference. The case management backend generates it on submission,
 * owning the format (RA-318: `AP` + year + agency + orgId + postcode
 * suffix + material prefix) and its uniqueness constraint. This
 * journey verifies the user-visible outcome:
 *   • A work item can be created without the user ever supplying a
 *     reference (the field is gone from the form).
 *   • The created work item carries a server-generated `AP`-prefixed
 *     reference, shown on the success banner and the detail page.
 *   • That server-generated reference is displayed as the card ref link on
 *     the applications list. (RA-324 phase-2 removed search-by-reference: the
 *     combined "Organisation name or ID" field matches organisation name or
 *     operator org id only, not the application reference.)
 */
describe('RA-219 — server-generated application reference', () => {
  let createdId
  let applicationReference

  before(async () => {
    await login.login()
    await workItems.goto()
    // createWorkItem never enters a reference — it reads the
    // server-generated one back from the success banner.
    ;({ id: createdId, applicationReference } = await workItems.createWorkItem({
      organisationName: 'Server Reference Recyclers Ltd',
      siteAddressLine1: '1 Server Way',
      siteAddressTown: 'Leeds',
      siteAddressPostcode: 'LS1 2AD',
      material: 'glass',
      tonnageBand: '0-500'
    }))
  })

  after(async () => {
    await login.logout()
  })

  it('returns a server-generated reference even though the client supplied none', () => {
    expect(applicationReference).toMatch(/^AP[A-Z0-9]+$/)
    expect(applicationReference).not.toBe(createdId)
  })

  describe('work item detail page', () => {
    before(async () => {
      await workItems.openWorkItem(createdId)
    })

    it('shows the server-generated reference in the retained reference block', async () => {
      // RA-295 removed the envelope summary list; the reference moved to the
      // block at the foot of the page and the label changed from "Application
      // ref" to "Application reference".
      const value = await detail.getSummaryValueByKey('Application reference')
      expect(value).toBe(applicationReference)
    })
  })

  describe('the generated reference on the applications list', () => {
    before(async () => {
      // RA-324 phase-2: the combined "Organisation name or ID" search matches
      // organisation name or operator org id — NOT the application reference
      // (that capability went away with the old Org ID search box), so the
      // item is located here by its organisation name. RA-299: a bare
      // goto() now pre-checks the "assigned to me" default, which
      // searchByOrg's form submit would carry through and exclude this
      // (unassigned) item — reset to an explicit empty state first so the
      // search isn't implicitly assignee-scoped.
      await workItems.resetFilters()
      await workItems.searchByOrg('Server Reference Recyclers Ltd')
    })

    it('renders the server-generated reference as the card ref link text', async () => {
      const linkText = await workItems.workItemLink(createdId).getText()
      expect(linkText).toBe(applicationReference)
    })
  })
})
