import { expect } from '@wdio/globals'
import login from '../page-objects/login.page.js'
import workItems from '../page-objects/work-items.page.js'
import detail from '../page-objects/work-item-detail.page.js'

/**
 * RA-219 — Application reference generated by the case management system.
 *
 * The client (BFF) no longer generates or submits an application
 * reference. The case management backend generates it on submission,
 * owning the format (RA-318: `AP` + year + agency + orgId + postcode
 * suffix + material prefix) and its uniqueness constraint. This
 * journey verifies the user-visible outcome:
 *   • A work item can be created without the user ever supplying a
 *     reference (the field is gone from the form).
 *   • The created work item carries a server-generated `AP`-prefixed
 *     reference, shown on the success banner and the detail page.
 *   • That server-generated reference is searchable.
 */
describe('RA-219 — server-generated application reference', () => {
  let createdId
  let applicationReference

  before(async () => {
    await login.loginAs('assign')
    await workItems.goto()
    // createWorkItem never enters a reference — it reads the
    // server-generated one back from the success banner.
    ;({ id: createdId, applicationReference } = await workItems.createWorkItem({
      organisationName: 'Server Reference Recyclers Ltd',
      siteAddressLine1: '1 Server Way',
      siteAddressTown: 'Leeds',
      siteAddressPostcode: 'LS1 1AA',
      material: 'glass',
      tonnageBand: '0-500'
    }))
  })

  after(async () => {
    await login.logout()
  })

  it('returns a server-generated reference even though the client supplied none', () => {
    expect(applicationReference).toMatch(/^AP[A-Z0-9]+$/)
    expect(applicationReference).not.toBe(createdId)
  })

  describe('work item detail page', () => {
    before(async () => {
      await workItems.openWorkItem(createdId)
    })

    it('shows the server-generated reference in the "Application ref" summary row', async () => {
      const value = await detail.getSummaryValueByKey('Application ref')
      expect(value).toBe(applicationReference)
    })
  })

  describe('search by the server-generated reference', () => {
    before(async () => {
      await workItems.goto()
    })

    it('finds the work item by its full generated reference', async () => {
      await workItems.searchByOrgId(applicationReference)
      const linkText = await workItems.workItemLink(createdId).getText()
      expect(linkText).toBe(applicationReference)
    })
  })
})
